### ISSUE TITLE
Should the top matches be paired?

### ISSUE THREAD

**Issue by smth** [jpoehnelt/eleventy-plugin-related#12]
Say I'm compare document A with documents A B C D and E; and document B is the most related. I would expect that comparing document B with A B C D and E would result in document A being the most related (I'm assuming the absolute match is somehow excluded). I'm not finding this to be the case. Is this to be expected?

**Comment by jpoehnelt** [comment]
I don't think it is expected with tfidf. Note this library ultimately ends up using https://github.com/NaturalNode/natural/blob/master/lib/natural/tfidf/tfidf.js internally.
