### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by smth** [jpoehnelt/eleventy-plugin-related#6]
This looks cool and I wanted to give it a try, but couldn't get it to work. I'm probably not using it correctly, perhaps the docs could be elaborated on a bit.

Using the example from the readme made 11ty throw a `Cannot read properties of undefined (reading 'map')` error. It seems to complain about any variable that happens to be in the template where the filter is used.

**Comment by smth** [comment]
I tried with and without arrays with the same result. I wasn't sure of the syntax though. Should the example in the readme just work if I replace `stories` with a collection that exists in my project (I'm assuming stories is a collection)? `doc.link` and `doc.text` don't sound like typical 11ty things. What do those represent?

Maybe a more concrete example would help. I guess something pretty standard would be:

- You have a collection called `posts`
- From a post template you want to compare the current post against all other posts in that collection, based on:
  - `title`
  - a custom bit of front matter, let's say `description`
  - and maybe the post `content`

**Comment by jpoehnelt** [comment]
Mind trying with v1.0.3? I added some better error messages to https://www.npmjs.com/package/related-documents.

**Comment by smth** [comment]
If I use use the code example verbatim I get the error `Error: documents must be an array`.

I still feel like the issue is not knowing how to use the plug-in though - how to tell it what files to look at (see my previous questions).

**Comment by smth** [comment]
That's useful thanks. That is more or less what I'd first tried. The thing that was catching me out it seems is assuming that this plugin had an inbuilt way to read the current page (because I don't think 11ty gives you that as a variable you can pass on?). I added a little hacky way to capture the current post, and things started working :)

For the benefit of anyone else landing here (or anyone who wants to tell me a better way to do this) here's what I did:

```
{% set currentPost = '' %}

{% for post in collections.posts %}
  {% if page.url == post.url %}
    {% set currentPost = post %}
  {% endif %}
{% endfor %}
```

Which would then be used like this:

```
{% set related = currentPost | relatedPosts(collections['posts']) %}
```

**Comment by gwillem** [comment]
Thanks for sharing this last example, however I cannot believe there is not a more elegant way to obtain the current post/page? @jpoehnelt, how is `post` in your blog initialized? Thanks!

**Comment by jpoehnelt** [comment]
You can always modify the filter function to return the source post. 

```js
eleventyConfig.addFilter("relatedPosts", function (doc, docs) {
    return related(doc, docs)
      .filter(({ relative }) => relative > 0.1)
      .map(d => ({from: doc, to: d.document, score: d.relative}));
});
```
